### PR TITLE
chore: pin autovalue temporarily and delete guava rule.

### PR DESCRIPTION
**Pull request by zhumin8**
disable renovate bot from updating autovalue temporarily.
current autovalue version is 1.10.4 ([here](https://github.com/googleapis/java-shared-config/blob/34164052444ed9bd40a0789ed020b45cf4da17fb/java-shared-config/pom.xml#L29))

This is for lts 7, and I will manually remove this disable later.

remove renovate config for guava as there is no guava version setup in this repo, instead, it is updated in sdk-platform-java [here](https://github.com/googleapis/sdk-platform-java/blob/56775a61a054fb67a15023481cd3d0a0cf2b0496/gapic-generator-java-pom-parent/pom.xml#L33).

### CODE REVIEW

**Comment by zhumin8** [comment]
> _Warning_: This pull request is touching the following templated files:
> 
> * renovate.json

Looks like renovate.json is excluded in https://github.com/googleapis/java-shared-config/blob/087d625231f57d183e325fc1c73c8a96bdeaf4de/owlbot.py#L32

**Review by lqiu96 — APPROVED** [review]

**Comment by lqiu96** [comment]
Error for graalvm CI:
```
Step #0 - "graalvm-a-build": Step 8/10 : RUN yum -y install terraform
Step #0 - "graalvm-a-build":  ---> Running in 9b2ba3508f68
Step #0 - "graalvm-a-build": Loaded plugins: ovl
Step #0 - "graalvm-a-build": No package terraform available.
Step #0 - "graalvm-a-build": Error: Nothing to do
Step #0 - "graalvm-a-build": The command '/bin/sh -c yum -y install terraform' returned a non-zero code: 1
```

I think this was resolved in https://github.com/googleapis/java-shared-config/pull/806. Can you pull it in and re-run the CI?

**Pull request merged**
