### PR TITLE
feat: update graal-sdk to 24 and graalvm-A to 21.x

### PR DESCRIPTION
**Pull request by mpeddada1**
Also verified locally with java-kms ([logs](https://gist.github.com/mpeddada1/ab78ad6de53126ad637759540a5b0078)). 

Noting two significant changes in PR:
- ~~- The `ITHttpAnnotation` test is marked as skipped in the showcase downstream check until https://github.com/googleapis/sdk-platform-java/issues/2695 is fixed.~~ https://github.com/googleapis/sdk-platform-java/issues/2695 has been fixed so we proceeded to keep this test in.
- The downstream java-spanner check is failing due to the recently added module `org.graalvm.sdk:nativeimage` being unaccounted for in the `ignoredDependencies` section of java-spanner's `maven-dependency-plugin`. We plan temporarily mark this check as optional to proceed with the update and include `org.graalvm.sdk:nativeimage` in the maven-dependency-plugin once `sdk-platform-java-config` has been updated in the repo. See https://github.com/googleapis/java-shared-config/pull/815#issuecomment-2086565890 for context.

### CODE REVIEW

**Comment by mpeddada1** [comment]
In JDK 21, `ITHttpAnnotation` fails with:
```
 [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.460 s <<< FAILURE! -- in com.google.showcase.v1beta1.it.ITHttpAnnotation
Step #1: [ERROR] com.google.showcase.v1beta1.it.ITHttpAnnotation.testComplianceGroup[Compliance Group Name: Fully working conversions, no resources] -- Time elapsed: 0.031 s <<< ERROR!
Step #1: com.google.api.gax.rpc.InvalidArgumentException: Bad Request
Step #1: 	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:52)
Step #1: 	at com.google.api.gax.httpjson.HttpJsonApiExceptionFactory.createApiException(HttpJsonApiExceptionFactory.java:76)
Step #1: 	at com.google.api.gax.httpjson.HttpJsonApiExceptionFactory.create(HttpJsonApiExceptionFactory.java:54)
Step #1: 	at com.google.api.gax.httpjson.HttpJsonExceptionCallable$ExceptionTransformingFuture.onFailure(HttpJsonExceptionCallable.java:97)
Step #1: 	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
Step #1: 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1130)
Step #1: 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
Step #1: 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1298)
Step #1: 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1059)
Step #1: 	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:809)
Step #1: 	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:92)
Step #1: 	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:74)
Step #1: 	at com.google.api.gax.httpjson.HttpJsonClientCalls$HttpJsonFuture.setException(HttpJsonClientCalls.java:132)
Step #1: 	at com.google.api.gax.httpjson.HttpJsonClientCalls$FutureListener.onClose(HttpJsonClientCalls.java:166)
Step #1: 	at com.google.api.gax.httpjson.HttpJsonClientCallImpl$OnCloseNotificationTask.call(HttpJsonClientCallImpl.java:552)
Step #1: 	at com.google.api.gax.httpjson.HttpJsonClientCallImpl.notifyListeners(HttpJsonClientCallImpl.java:391)
Step #1: 	at com.google.api.gax.httpjson.HttpJsonClientCallImpl.deliver(HttpJsonClientCallImpl.java:318)
Step #1: 	at com.google.api.gax.httpjson.HttpJsonClientCallImpl.setResult(HttpJsonClientCallImpl.java:164)
Step #1: 	at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:149)
Step #1: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
Step #1: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Step #1: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
Step #1: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Step #1: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Step #1: 	at java.base/java.lang.Thread.run(Thread.java:1583)
Step #1: 	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
Step #1: 		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
Step #1: 		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
Step #1: 		at com.google.showcase.v1beta1.ComplianceClient.repeatDataBody(ComplianceClient.java:442)
Step #1: 		at com.google.showcase.v1beta1.it.ITHttpAnnotation.testComplianceGroup(ITHttpAnnotation.java:142)
Step #1: 		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Step #1: 		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Step #1: 		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
Step #1: 		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
Step #1: 		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
Step #1: 		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
Step #1: 		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
Step #1: 		at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
Step #1: 		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
Step #1: 		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
Step #1: 		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
Step #1: 		at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
Step #1: 		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
Step #1: 		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
Step #1: 		at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
Step #1: 		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
Step #1: 		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
Step #1: 		at org.junit.runners.Suite.runChild(Suite.java:128)
Step #1: 		at org.junit.runners.Suite.runChild(Suite.java:27)
Step #1: 		at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
Step #1: 		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
Step #1: 		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
Step #1: 		at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
Step #1: 		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
Step #1: 		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
Step #1: 		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
Step #1: 		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
Step #1: 		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
Step #1: 		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
Step #1: 		at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
Step #1: 		at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
Step #1: 		at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
Step #1: 		at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
Step #1: 		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
Step #1: 		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
Step #1: 		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
Step #1: 		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
Step #1: 		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
Step #1: 		at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
Step #1: 		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
Step #1: 		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
Step #1: 		at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
Step #1: 		at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
Step #1: 		at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
Step #1: 		at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
Step #1: 		at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
Step #1: 		at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
Step #1: 		at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
Step #1: 		at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
Step #1: 		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Step #1: Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
Step #1: POST http://localhost:7469/v1beta1/repeat:body
Step #1: {"error":{"code":400,"message":"error reading body params '*': proto: syntax error (line 1:513): invalid value \u0000","details":null,"Body":"","Header":null,"Errors":null}}
Step #1: 	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
Step #1: 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
Step #1: 	at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:115)
Step #1: 	... 6 more
```

**Comment by mpeddada1** [comment]
Running the same test multiple times locally on JDK 21 shows this test to failing 15/20 times
   
Screenshot 2024-04-25 at 6 29 20 PM

**Comment by mpeddada1** [comment]
Created issue to track ITHttpAnnotation failure in https://github.com/googleapis/sdk-platform-java/issues/2695

**Review by suztomo — APPROVED** [review]

**Comment by burkedavison** [comment]
Do not merge until https://github.com/googleapis/sdk-platform-java/issues/2695 is resolved

**Comment by Joanna2473** [comment]
.

**Comment by Joanna2473** [comment]
.

**Comment by Joanna2473** [comment]
L

**Comment by burkedavison** [comment]
@mpeddada1 : Do you agree this can now be merged?

**Comment by mpeddada1** [comment]
Following up on https://github.com/googleapis/java-shared-config/pull/815#issuecomment-2086565890, looked into adding the maven-dependency-plugin settings to native-image-shared-config in https://github.com/googleapis/java-shared-config/pull/815#issuecomment-2086565890 but these settings end up getting overridden by the child pom so it doesn't address the issue we are facing with java-spanner. 

Current approach: Include ignoreDependencies property in native-image-shared-config to then be included downstream when this artifact is released and updated in java-spanner. The side effect of this is that the java-spanner repo will temporarily see a failure.

**Review by burkedavison — APPROVED** [review]

**Pull request merged**
