### PR TITLE
chore: Renaming  `auto-value-annotation.version` to `auto-value.version`

### PR DESCRIPTION
**Pull request by ddixit14**

### CODE REVIEW

**Comment by ddixit14** [comment]
1. **downstream / dependencies (11, java-pubsub)** is failing with error:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project google-cloud-pubsub: Resolution of annotationProcessorPath dependencies failed: version can neither be null, empty nor blank.
```

2.   **downstream / javadoc-with-doclet (java-bigtable)** is failing with error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.0:aggregate (default-cli) on project google-cloud-bigtable-parent: Execution default-cli of goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.0:aggregate failed: If a non-null excludes list is given, all elements must be non-null -> [Help 1]
```

**Comment by suztomo** [comment]
The pubsub one is concerning. Can you check whether the java-pubsub project references the variable?

downstream / javadoc-with-doclet (java-bigtable) is known to fail for now.

**Comment by blakeli0** [comment]
> The pubsub one is concerning. Can you check whether the java-pubsub project references the variable?
> 
> downstream / javadoc-with-doclet (java-bigtable) is known to fail for now.

Looks like [they](https://github.com/googleapis/java-pubsub/blob/main/google-cloud-pubsub/pom.xml#L183-L199
) are, we should remove the usage there.

**Comment by suztomo** [comment]
Confirming whether the maven-compiler-plugin configuration at java-pubsub is really needed or not https://github.com/googleapis/java-pubsub/pull/1761.

**Comment by suztomo** [comment]
I merged https://github.com/googleapis/java-pubsub/pull/1761  in pubsub. I just restarted "downstream / dependencies (11, java-pubsub) " job.

**Comment by ddixit14** [comment]
**downstream / dependencies (11, java-pubsub)** has passed now. Merging the PR.

**Review by suztomo — APPROVED** [review]

**Review by blakeli0 — APPROVED** [review]

**Pull request merged**
